### ISSUE TITLE
addon.py-recordings_dir() ei osaa ryhmitellä kansioihin kaikkia sisältöjä

### ISSUE THREAD

**Issue by iljajetsu** [munselo/plugin.video.dnatv#2]
mm. 
Ritari Ässä  (Vitonen)(seuraavat jaksot la   2 jaksoa)
Elämä pelissä (Yle 1) (seuraavat jaksot su, ma, ti)

Johtuisiko siitä että kaksiosainen nimi ja toisessa osassa ääkkösiä?  koska esimerkiksi 
Ryhmä Hau menee ihan oikein kaikki saman otsikon alle, vaikka onkin kaksiosainen nimi ja ääkkösiä, mutta vain ensimmäisessä osassa.

Niin, ja kiitokset hyvästä plugarista :+1:  :)

Jos tuntuu että et halua enää kuulla mitään virheilmoituksia, niin jätä vaan huomiotta nämä. Python ei ole itselle tutuin kieli, mutta kyllä näitä ehkä jossain vaiheessa saa korjattua kun vähän aikaa miettii.

Ainiin, toinen asia josta en vielä tee tikettiä, kun ei ole tarkempaa tietoa.
Jostain syystä Kodi kaatuu, kun on ladannut 3-5 elokuvaa putkeen paikalliselle koneelle, siitä en vielä ole saanut kiinni mistä johtuu. Käytännössä kaatuu heti sen jälkeen kun viimeisin lataus on valmis. Logille ei tulostu mitään erikoista, osx:n kaatumisilmoitus sanoo että jotain pythoniin liittyvää vapautusta se on tekemässä.

**Comment by munselo** [comment]
Toivottavasti ei ole mitään sivuvaikutuksia tuolla korjauksella. Hyvähän se on tietää jos jotain vikaa ilmenee, eli tee vain virheilmoituksia jatkossakin.

Tuota dnatv.py scriptiä voi käyttää tallenteiden lataamiseen suoraan komentoriviltäkin alla esitetyllä tavalla. Edellyttää toki että koneella on python 2.jotain ja requests asennettuna.

dnatv.py käyttäjänimi salasana dnatv/booxtv -download hakusana

Tuolla saa ladattua kaikki tallenteet joista hakusana löytyy. Yksittäisen tallenteen voi ladata käyttämällä hakusanana programUid:tä joka on mallia "42249-529-4282-07-2016" ja näkyy selaimessa.
