### ISSUE TITLE
Live-tv does not work. 

### ISSUE THREAD

**Issue by PetteriLah** [munselo/plugin.video.dnatv#3]
Live-tv Channel listing does not work.

**Comment by munselo** [comment]
Can you please be a little more specific. 

If the list opens but is empty. Try following

There is a menu with an option to show only unwatched. Live feeds are marked as watched after opening and therefore hidden if that option is selected. I have not even tried to find out if that's possible to prevent or mark all feeds unwatched while creating listitems.

**Comment by PetteriLah** [comment]
No it not open channel list. It says something come wrong.
I have two box, same issue. DNAtv official website my account works.
This addons works fine yesterday.

**Comment by munselo** [comment]
can you try to log out from contex menu and try again after that. What version of kodi you are using? I tried to watch Investigation Discovery channel today and had no problem.

**Comment by PetteriLah** [comment]
Now it works!
Kodi 17.0 and 16.1
changing service dnatv to booxtv and try again after that and then change service back to dnatv fix the problem

Here is couple line of my debug file when issue was on.
ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=liveTV
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=liveTV) failed
ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=recordings
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=recordings) failed
ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=liveTV
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=liveTV) failed
ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=liveTV
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=liveTV) failed

**Comment by munselo** [comment]
Thanks for your information.

I know that sometimes for some unkown reason this plugin stops working and usually logout from contex menu helped. I think it has something to do with session info stored at settings file.  Last update added cleaning of all the session and temporary info after failing to enter live or recordings folder that's when you hit the notification "something went wrong". So i can only wonder why changing service solved the problem.
