### ISSUE TITLE
Live TV-channels missing

### ISSUE THREAD

**Issue by StBeBe** [munselo/plugin.video.dnatv#4]
I'm using this DNATV-addon with kodi on RPi to watch BooxTV.

The problem is that Yle2 and Yle1 -channels disappeared from live-tv -channel list (Yle2 last weekend and Yle1 today). YleFem and YleTeema are still present at the list. I just tested that I can still watch Yle2 liveTV-broadcast with booxTV-app on android.

Do you have any ideas what is happening here?

**Comment by munselo** [comment]
There should be a menu with an option to show only unwatched. Live feeds are marked as watched after opening and therefore hidden if that option is selected.  Change option to show all from show unwatched.
