### ISSUE TITLE
Tallenteet eivät näy (Booxtv)

### ISSUE THREAD

**Issue by StBeBe** [munselo/plugin.video.dnatv#6]
Hei

Päivitin juuri Raspbianin Kodi 18-versioon  ja huomasin että booxtv:n tallenteet eivät enää näy dnatv-pluginin kautta. Live-tv näkyy hyvin, mutta tallenteet-kansioon mentäessä heittää virheilmoituksen.

Liitin kodin logitiedoston oheen jo siitä on apua.

[kodi.log](https://github.com/munselo/plugin.video.dnatv/files/2886335/kodi.log)

**Comment by munselo** [comment]
Moi

Toivottavasti toimii uusimmalla versiolla. Ongelma liittyi kielivalintoihin ja päiväyksiin.

**Comment by StBeBe** [comment]
Moro!

Kokeilin tuolla uusimmalla versiolla, mutta ei suostunut tuollakaan toistamaan tallenteita.

Suorat lähetykset näkyvät kyllä tuollakin hyvin.

Tässä lokitiedosto: 
[kodi.log](https://github.com/munselo/plugin.video.dnatv/files/2942810/kodi.log)

**Comment by StBeBe** [comment]
Moi

Ongelma olikin tässä päässä...

Ihmettelin kun tallenteet näkyivät ihan hyvin toisella RPi3+:llani samalla kodi18 ja raspbian versiolla. Kokeilin säädellä kaikkea mahdollista kieli-ja aika-asetuksiin liittyvää raspbianista ja kodista ja uudelleen asensin kodin.

Ongelma ratkesi lopulta kun muutin raspbianin asetuksista localisation/Locale-valikosta character setin UTF-8 -> ISO8859-1...

Nyt homma pelittää. Kiitos sinulle (tällä kertaa nyt turhasta ) vaivannäöstä ja loistavasta plugarista!
